### ISSUE TITLE
Onboarding : Merge and refine steps 1 and 2

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/mobile_poc#120]
cf. https://docs.google.com/document/d/1OOQ8p1zgexN8FBitWXtKOkdAVjng3bqKfAuQLEBQ5Ss/edit#heading=h.wwagmncmj9p9 

Affinage à discuter - opportunité à l'intégrer à telle ou telle version aussi

**Comment by prk-dismoi** [comment]
Zeplin link: zpl.io/V13xkWJ
