### ISSUE TITLE
Reassure user about his data just before / when asking accessibilty authorization

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/mobile_poc#121]
Not MVP 
**Issue description**
When I switch on Accessibilité authorization for DisMoi, Android warns me that I am sharing a lot of data about on my phone. This might make some users jump. 

**Ideas**
1. kind of toast message in accessibilty menu 
See button mapper example : https://drive.google.com/drive/u/0/folders/0B-kleyAt-JBeVHpnU1dqaVZfLTQ?resourcekey=0-P7WHeKM7o6EK0PIWvErpxw 

2. message just before going there 
See Button Mapper example https://drive.google.com/drive/u/0/folders/0B-kleyAt-JBeVHpnU1dqaVZfLTQ?resourcekey=0-P7WHeKM7o6EK0PIWvErpxw

**Comment by prk-dismoi** [comment]
duplicate issue #149

**Comment by prk-dismoi** [comment]
Closing this issue, which is now replaced by issues #149 and #159
