### ISSUE TITLE
Profiles list : UI refinements

### ISSUE THREAD

**Issue by MaartenLMEM** [dis-moi/mobile_poc#123]
List of refinments : 
1. Text is currenlty center : align it to left (see mockup)
2. ...
3. ...

**Comment by prk-dismoi** [comment]
I have made an Android specific export of the Sketch design files into Zeplin, which will help for an accurate layout.

@felix-lambert, access below:

- Zeplin web link: https://zpl.io/b6AP7oK
- Zeplin App link: zpl://project?pid=60e6d676382a1c713e9ba58e

**Comment by felix-lambert** [comment]
I think this issue is quite general. Is it possible to split this ticket into smaller issues and link it with the zeplin layout?

**Comment by prk-dismoi** [comment]
Roger that, I'm splitting the tickets, closing this one.
