### ISSUE TITLE
"Open" button after install doesnt work

### ISSUE THREAD

**Issue by prk-dismoi** [dis-moi/mobile_poc#161]
version 1.0.4
samsung galaxy s8

After installing the app, the "open" or "done" buttons at the bottom right of the screen do not work.

**Comment by prk-dismoi** [comment]
![image](https://user-images.githubusercontent.com/80406294/124937689-eb2e3900-e007-11eb-9eba-44360423bdba.png)

**Comment by felix-lambert** [comment]
Hello @prk-dismoi I think it's a bug related to firebase no? Can you be more specific?

**Comment by prk-dismoi** [comment]
Hey @felix-lambert I don't know if this is a Firebase or Android view, I'm not familiar with either and there's no indication on screen. If it's not an Android screen we can ignore.

**Comment by prk-dismoi** [comment]
Could be a firebase issue. We will test the new APK in Play Store and review the installation process there.

**Comment by felix-lambert** [comment]
Do you want the apk? Or can I access the play store to add it?

**Comment by prk-dismoi** [comment]
Got APK 1.0.5. trying to set it up now.

**Comment by prk-dismoi** [comment]
@felix-lambert I'm getting an error message from google Play when I upload 1.0.5 APK:

![image](https://user-images.githubusercontent.com/80406294/125850651-a9e9d85b-0533-4b68-948e-5e4a777812b6.png)

Help file about app signing: https://developer.android.com/studio/publish/app-signing

**Comment by prk-dismoi** [comment]
closing this ticket, we will reopen if this proves to be an Android and not a Firebase issue.
