### ISSUE TITLE
Contributors list UI refinement

### ISSUE THREAD

**Issue by prk-dismoi** [dis-moi/mobile_poc#176]
Align UI with Zeplin web 360x640 screens:

web: https://zpl.io/25jgRA8
app: zpl://screen?pid=60b9f2b62640ada4e239101b&sid=60f08fb4bbcb4d69aed7e165

**Comment by prk-dismoi** [comment]
![Screenshot 2021-07-15 at 10 55 03](https://user-images.githubusercontent.com/80406294/125774232-0f104132-a4e9-46b1-9b8c-97665243fa31.png)

**Comment by prk-dismoi** [comment]
@felix-lambert as discussed, above are links to the new 360x640 Zeplin web screens for the contributors list.
Also attached a video to show the scrolling in action.

**Comment by felix-lambert** [comment]
The web screen size fits
