### ISSUE TITLE
Bubble stays when Chrome is closed

### ISSUE THREAD

**Issue by prk-dismoi** [dis-moi/mobile_poc#184]
When I close Chrome from a page that displays the Dismoi Bubble, the bubble remains on screen.

**Comment by prk-dismoi** [comment]
![image](https://user-images.githubusercontent.com/80406294/126131862-95094991-c40f-4402-9eb4-044ce4f62268.png)

**Comment by felix-lambert** [comment]
Thanks for finding this bug. I think I managed to solve it but not sure. Can you also give the sdk version when you find a bug?

**Comment by prk-dismoi** [comment]
sorry my bad. 1.0.5, still on my Samsung Galaxy S8.
