### ISSUE TITLE
Force closing the app deactivates accessibility

### ISSUE THREAD

**Issue by prk-dismoi** [dis-moi/mobile_poc#202]
### 1. Configuration

* Device brand `(Samsung, etc...)`: Samsung
* Device name `(Galaxy S8, etc...)`: Galaxy S8
* Device model number `(settings > about phone)`: SM - G950F
* Android OS version `(settings > about phone > Android version)`: 9
* Browser: **Chrome**
* Browser version `(settings > apps > Chrome > bottom of page)`: 91.0.4472.164
* Dismoi App version `(settings > apps > Dismoi > bottom of page)`: 1.0.7 (6)
---
### 2. Describe the current behavior:

When I force close the app, it disables the accessibility setting

---
### 3. Steps to reproduce:

    a. go to settings > apps > Dismoi
    b. Force close
    c. reopen Dismoi app
---
### 4. Describe the expected behavior

The accessibility settings should stay ON

---
### 4. Additional details (optional)

Write here...

**Comment by felix-lambert** [comment]
I don't think it's possible to keep the accessibility on if you force close. I think android automatically turns off accessibility if you force close the app.

**Comment by MaartenLMEM** [comment]
I just made the test on Amazon Antidote : same result, it deactivates accessibility authorization.

**Comment by prk-dismoi** [comment]
Checked this one, it's standard behaviour from Android. Some have tried to circumvent, only to create more problems. The scenario is covered by UX and going back to the authorisation screen on the Dismoi app will be no surprise. Closing this issue.

**Comment by JalilArfaoui** [comment]
The only reasonable response seems to be «do not have to force close the app»
