### ISSUE TITLE
Open a google play account

### ISSUE THREAD

**Issue by felix-lambert** [dis-moi/mobile_poc#24]
I need a dismoi google play account so that I can put the app in private

Maybe this is something @christpet that you could do? 

Creating the branding, communication, marketing... Everything can be done in google play

**Comment by christpet** [comment]
@felix-lambert thanks for putting this on the project - will do this in the next week or so!

**Comment by prk-dismoi** [comment]
@felix-lambert can you assign this ticket to me? 
@christpet do i pick this one up from the start or did your start the process with Google already?
lmk tx

**Comment by prk-dismoi** [comment]
@felix-lambert could you grant me access to move this ticket between columns? will move to TO DO

**Comment by felix-lambert** [comment]
Done

**Comment by prk-dismoi** [comment]
@felix-lambert the Dismoi Play store account has now been opened. I've invited you, you should have an email.
